### PR TITLE
Make ProviderSpec credentialsSecretRef optional

### PR DESCRIPTION
**Pull request by hasheddan**
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

### Description of your changes

Makes the `credentialsSecretRef` field optional in `ProviderSpec` such that alternative auth methods can be utilized without having to reference a `Secret`.

Ref: https://github.com/crossplaneio/stack-aws/pull/126#discussion_r376681446

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [ ] Updated any relevant [documentation], [examples], or [release notes].
- [ ] Updated the RBAC permissions in [`clusterrole.yaml`] to include any new types.

[documentation]: https://github.com/crossplaneio/crossplane/tree/master/docs
[examples]: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplaneio/crossplane/tree/master/PendingReleaseNotes.md
[`clusterrole.yaml`]: https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/templates/clusterrole.yaml

### CODE REVIEW

**Comment by hasheddan** [comment]
@negz that is correct :+1: I am happy to make those updates. We could also not make it a pointer, then we would just get empty strings and fail to get the secret, but I feel like that would go against our conventions so I would prefer to just make the updates if that sounds good

**Comment by negz** [comment]
@hasheddan SGTM - I imagine the updates should be fairly mechanical.

**Comment by hasheddan** [comment]
@negz anything else needed here?

**Comment by negz** [comment]
Nope - just forgot to hit merge. :)

**Comment by hasheddan** [comment]
@negz thanks :)

**Pull request merged**
