### PR TITLE
portable class: embed all necessary fields

### LINKED ISSUE #26: Make portable classes subtypes of runtimev1alpha1.PortableClass
### What problem are you facing?

Currently every portable class is a distinct type that embeds `runtimev1alpha1.PortableClass`, with the exact same shape. For example:

```go
type PortableClass struct {
	NonPortableClassReference *corev1.ObjectReference `json:"classRef,omitempty"`
}

type RedisClusterClass struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	runtimev1alpha1.PortableClass `json:",inline"`
}
```

### How could Crossplane help solve your problem?

We could probably write a little less code by making them a type (in the Go sense) of PortableClass, e.g.:

```go
type PortableClass struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	NonPortableClassReference *corev1.ObjectReference `json:"classRef,omitempty"`
}

type RedisClusterClass PortableClass
```

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Embeds all subfields in `PortableClass`. Crossplane will need to bump `crossplane-runtime` dependency version and remove subfields from the portable class types to complete change.

Fixes #26 

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation], [examples], or [release notes].
- [x] Updated the RBAC permissions in [`clusterrole.yaml`] to include any new types.

[documentation]: https://github.com/crossplaneio/crossplane/tree/master/docs
[examples]: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplaneio/crossplane/tree/master/PendingReleaseNotes.md
[`clusterrole.yaml`]: https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/templates/clusterrole.yaml

### CODE REVIEW

**Comment by hasheddan** [comment]
@negz this has not been tested, but I will do so now

**Comment by hasheddan** [comment]
@negz setting the underlying type of portable classes to `PortableClass` does not allow it to satisfy the `PortableClass` interface because types do not inherit the methods of their underlying types. However, we can still make the `PortableClass` type the only thing that is embedded in individual portable class types. I have implemented here for your reference: https://github.com/hasheddan/crossplane/commit/b05fd346b17045e8bd47183044108c4566d1e61f

**Comment by negz** [comment]
@hasheddan Thanks for trying that out! It's possible that using a [type alias](https://go.googlesource.com/proposal/+/master/design/18130-type-alias.md) would work, but I think that would be an abuse of that feature.

On reflection I'm slightly inclined to abandon this effort. When I see that a struct embeds `TypeMeta` and `ObjectMeta` it's immediately obvious to me that it intends to be a Kubernetes resource. It didn't occur to me that this might make the code a little less obvious when I wrote #26, but seeing how the actual code reads in the context of https://github.com/hasheddan/crossplane/commit/b05fd346b17045e8bd47183044108c4566d1e61f makes me think the current pattern is better than the slight optimisation of not having to include type and object metadata. What do you think?

**Comment by hasheddan** [comment]
Agreed! Was worth a shot :)

**Pull request closed without merging**
